### ISSUE TITLE
Windows 10 not displaying correct Status Code Error 500

### ISSUE THREAD

**Issue by yidakee** [ResistancePlatform/resistance-platform-release#2] opened 2019-09-11 11:23 UTC
Both wallet v 2.2.2 - On MacOs, this msg pops up

<img width="555" alt="Screenshot 2019-09-11 at 11 52 25" src="https://user-images.githubusercontent.com/16577836/64693289-d5dd3780-d48e-11e9-9eb4-34adb90a1639.png">

The equivalent action on Windows 10 only displays

"Error Creating The Order - Can't Create A Limit Order"

**Comment by lukewegryn** [comment] 2019-12-02 00:07
This error appears to be a duplicate of the error in #3. Please update to the newest Resistance version as this should be fixed. Closing.

**Closed as completed by lukewegryn** 2019-12-02 00:07 UTC
